FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore
RUN dotnet build --no-restore -c Release

FROM build AS testrunner
WORKDIR /src
CMD ["dotnet", "test", "--no-restore", "--no-build", "--logger:trx"]
